kind: CronJob
apiVersion: batch/v1
metadata:
  name: client-job
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: client-c
            image: santisbon/speedtest:latest
            imagePullPolicy: Always
            env:
            - name: TZ
              value: "America/Chicago"
            - name: TIME_SERIES_HOST
              value: {{ .Release.Name }}-influxdb-svc
            - name: TIME_SERIES_PORT
              value: {{ .Values.influxdbport | quote }}
            - name: TIME_SERIES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secure-config
                  key: influxdb.username
            - name: TIME_SERIES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secure-config
                  key: influxdb.password
            - name: TIME_SERIES_DATABASE
              value: {{ .Values.bucket }}
            - name: TIME_SERIES_ORG
              value: {{ .Values.org | quote }}
          restartPolicy: OnFailure