kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-client-deploy
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: speedtest
      tier: client
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: speedtest
        tier: client
    spec:
      containers:
      - name: client-c
        image: santisbon/speedtest:latest
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "America/Chicago"

# TODO: Set env variables from Secrets for influxdb credentials