kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-secure-config
type: Opaque
data:
  influxdb.username: {{ .Values.influxdbuser | b64enc }}
  influxdb.password: {{ .Values.influxdbpassword | b64enc }}
  influxdb.token: {{ .Values.influxdbtoken | b64enc }}