kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-var-lib-influxdb2-pv
  labels:
    directory: var-lib-influxdb2
spec:
  storageClassName: {{ .Release.Name }}-local-sc
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /var/lib/influxdb2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.nodeHostname | quote }}

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-etc-influxdb2-pv
  labels:
    directory: etc-influxdb2
spec:
  storageClassName: {{ .Release.Name }}-local-sc
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /etc/influxdb2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.nodeHostname | quote }}
