kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-var-lib-influxdb2-pvc
spec:
  storageClassName: {{ .Release.Name }}-local-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      directory: var-lib-influxdb2

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-etc-influxdb2-pvc
spec:
  storageClassName: {{ .Release.Name }}-local-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      directory: etc-influxdb2