kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-influxdb-svc
spec:
  clusterIP: None
  selector:
    app: speedtest
    tier: db
  ports:
  - port: {{ .Values.influxdbport }}
  
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-var-lib-influxdb2-pvc
spec:
  storageClassName: {{ .Release.Name }}-local-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      directory: var-lib-influxdb2

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-etc-influxdb2-pvc
spec:
  storageClassName: {{ .Release.Name }}-local-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      directory: etc-influxdb2

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-influxdb-deploy
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: speedtest
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: speedtest
        tier: db
    spec:
      containers:
      - name: influxdb-c
        image: influxdb
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: "America/Chicago"
        - name: DOCKER_INFLUXDB_INIT_MODE
          value: {{ .Values.initMode }}
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secure-config
              key: influxdb.username
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secure-config
              key: influxdb.password
        - name: DOCKER_INFLUXDB_INIT_ORG
          value: {{ .Values.org | quote }}
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          value: {{ .Values.bucket }}
        - name: DOCKER_INFLUXDB_INIT_RETENTION
          value: {{ .Values.retention }}
        volumeMounts:
        - name: var-lib-influxdb2-vol
          mountPath: "/var/lib/influxdb2"
        - name: etc-influxdb2-vol
          mountPath: "/etc/influxdb2"
      volumes:
      - name: var-lib-influxdb2-vol
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-var-lib-influxdb2-pvc
      - name: etc-influxdb2-vol
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}--etc-influxdb2-pvc
      